alias code=vscodium
alias sdup='sudo systemctl start'
alias sddown='sudo systemctl stop'
alias sdrestart='sudo systemctl restart'
alias sdstatus='systemctl status'
alias dcs='docker-compose'
alias dcsru='dcs run --rm -u 1000:1000'
alias dci='docker images'
alias dcps='docker ps -a'
alias xopen=xdg-open
